version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bookrental-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # 렌더 환경변수를 사용
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # 렌더 환경변수를 사용
      MYSQL_USER: ${MYSQL_USER}  # 렌더 환경변수를 사용
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # 렌더 환경변수를 사용
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: bookrental-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_ADDON_HOST}:${MYSQL_ADDON_PORT}/${MYSQL_ADDON_DB}?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ADDON_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ADDON_PASSWORD}
    ports:
      - "8080:8080"
